import request from '@/utils/request'

export const adminLogin = (data) => request.post('/admin/login', data)
export const getUsers = (params) => request.get('/admin/users', { params })
export const getUserDetail = (id) => request.get(`/admin/users/${id}`)
export const updateUserStatus = (id, status) => request.put(`/admin/users/${id}/status`, null, { params: { status } })
export const getPresets = () => request.get('/admin/presets')
export const updatePreset = (id, data) => request.put(`/admin/presets/${id}`, data)
export const createPreset = (data) => request.post('/admin/presets', data)
export const deletePreset = (id) => request.delete(`/admin/presets/${id}`)
export const getPlatformPresets = () => request.get('/admin/platform-presets')
export const createPlatformPreset = (data) => request.post('/admin/platform-presets', data)
export const updatePlatformPreset = (id, data) => request.put(`/admin/platform-presets/${id}`, data)
export const deletePlatformPreset = (id) => request.delete(`/admin/platform-presets/${id}`)
export const rechargeUser = (id, data) => request.post(`/admin/users/${id}/recharge`, data)
export const getRechargeRecords = (id) => request.get(`/admin/users/${id}/recharge-records`)
export const getConfigs = () => request.get('/admin/configs')
export const updateConfig = (id, configValue) => request.put(`/admin/configs/${id}`, { configValue })
export const getRedeemCodes = (params) => request.get('/admin/redeem-codes', { params })
export const generateRedeemCodes = (data) => request.post('/admin/redeem-codes/generate', data)
